### ISSUE TITLE
[2.1.14] document number hook broken

### ISSUE THREAD

**Issue by Zeromax** [isotope/core#1485]
since https://github.com/isotope/core/commit/b8fba25c30eb9d91d47bcda5501b289f025f143c the return value from the `$GLOBALS['ISO_HOOKS']['generateDocumentNumber']` is not used anymore.

I have to save the value by my own cause saving of the value is moved inside of the try catch.
Otherwise my modified `document_number` would never be saved.

**Comment by aschempp** [comment]
This does not make sense to me, as the try-catch should not change anything, and the hook is not even in those code lines. Can you further explain the problem?

**Comment by Zeromax** [comment]
Yes it changes it ;) cause you moved the try catch inside the if clause -> https://github.com/isotope/core/blob/b8fba25c30eb9d91d47bcda5501b289f025f143c/system/modules/isotope/library/Isotope/Model/ProductCollection.php#L1334

And so the Database update itself.

**Comment by aschempp** [comment]
That's not true. Check out the diff without whitespaces: https://github.com/isotope/core/commit/b8fba25c30eb9d91d47bcda5501b289f025f143c?w=1

The if statement is here since every version 2.x of Isotope: https://github.com/isotope/core/commit/53028b095e30fbce386974c9040895f73a72213a#diff-0f55d18c670385e4d53dba5ad92a381aR1378

**Comment by aschempp** [comment]
Hah! Now I realized the problem. You're right, sorry, my fault.

**Comment by Zeromax** [comment]
@aschempp No problem. It is a bit tricky and took some time for me to see it too ;)

**Comment by aschempp** [comment]
Fixed in 2d2bae8c788f8b8e2dbb0cd5782d98d7a42c16f5
