### ISSUE TITLE
Rechteverwaltung: Anlegen von neuen Produkttypen, Konfigurationen etc. nicht möglich

### ISSUE THREAD

**Issue by mbuchholz** [isotope/core#1503]
Wenn man in der Rechteverwaltung einem Benutzer das Anlegen erlaubt, ist es trotzdem nicht möglich.
Als Beispiel nehme ich mal das Anlegen eines neuen Produkttyps.
Sobald ich diesen anlegen möchte erhalte ich die Fehlermeldung *Es ist ein Fehler aufgetreten*. Logisch, da versucht wird ein neuer Produkttyp anzulegen, aber das Recht für den Zugriff auf den gerade angelegten Produkttyp fehlt. Das sagt mir auch das System-Log:
```
[06.08.2015 10:02] Not enough permissions to edit product type ID "9"
[06.08.2015 10:02] A new entry "tl_iso_producttype.id=9" has been created
```

Ich habe das ganze auch mal mit einem News-Archiv ausprobiert, da dort die Rechtevergabe ähnlich ist.
Dort wird automatisch das Recht für den Zugriff auf dieses Archiv gesetzt.

**Comment by aschempp** [comment]
@qzminski @Toflar can we build a generic solution for that into Haste ?

**Comment by Toflar** [comment]
For what? :D

**Comment by aschempp** [comment]
Updating permissions in the group settings (like the Contao core does).

**Comment by aschempp** [comment]
@mbuchholz welche Isotope-Version verwendest du? Die entsprechende Prüfung scheint nämlich schon lange eingebaut…

**Comment by matejjurancic** [comment]
Tut mir leid, dass ich auf Englisch schreiben werde ...

I am facing the same problem as @mbuchholz. When a non-admin user with (group) permission to add new Product Type wants to add new product type it is created but can not be edited (similar log entries as above). I already had this problem with Contao 3.2 and Isotope 2.1.5 and it persists also after I upgraded both Contao (to 3.5.6) and Isotope (to 2.3.3).

From what I gathered from code debugging I suspect the problem is with `Isotope\Backend\Permission->addNewRecordPermissions` function, specifically with `$newRecords` key `tl_iso_group` within `if` clause on line 36. Changing it to `tl_iso_producttype` seems to resolve the problem.

**Comment by aschempp** [comment]
Oh well… thanks for the hint! That obviously was the problem, will be fixed in the next release.
