### ISSUE TITLE
[2.3.4] Fehlermeldung bei Benachrichtigungsversand unspezifisch

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1679]
Wenn beim Benachrichtigungsversand ein Fehler auftritt, ist die in tl_log protokollierte Fehlermeldung sehr unspezifisch und enthält keine konkreten Angaben zum Fehler:

> Details:	Error sending new order notification for order ID xxx
> Funktion:	Isotope\Model\ProductCollection\Order::checkout

**Comment by aschempp** [comment]
@Toflar @qzminski any idea if we can do something about that?

**Comment by Toflar** [comment]
The notification center tries to send each message and each message itself adds log entries. Basically the said log entry is the global one for the notification but there should be more?

**Comment by Mynyx** [comment]
There is only one log entry (and the normal log entry "New order ID x has been placed") in this case.

**Comment by Toflar** [comment]
Must be a very specific error that is not handled properly. That must be an exception to the rule. Can you maybe elaborate why it could not be sent?

**Comment by creatingo** [comment]
I had same issue with sending new order notification. Enabled "displayErrors" in localconfig gives me (just after "confirmOrder")

Warning: escapeshellarg() has been disabled for security reasons in vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php on line 250
. . .
By using SMTP server instead of the PHP mail() function Notifications works.
(Contao 3.5.15, Isotope 2.4.0-beta1, PHP 5.4)

**Comment by aschempp** [comment]
So it's a local misconfiguration.

**Comment by Mynyx** [comment]
test@example.partners

**Comment by Mynyx** [comment]
In the case of creatingo it is a local misconfiguration, but not in general.

You could reproduce the issue  for example with the customer email address ``test@example.partners``. It looks like that it is regarding to special TLDs.
