### ISSUE TITLE
[2.4.0] Placing an order with PDF don't work with Contao 4

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1763]
`[2017-02-09 10:12:57] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require_once(): Failed opening required '/home/public_html/domain.com/system/config/tcpdf.php' (include_path='.:/opt/alt/php71/usr/share/pear') at /home/public_html/domain.com/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Document/Standard.php:76)"} []`

**Comment by aschempp** [comment]
Fixed in 549ab47e68d8a811f235e422f7836d18bf24b271

**Comment by leofeyer** [comment]
The actual problem was that the symlink was missing (see contao/core-bundle#719), so you should revert the fix. The file being present in `system/config` is covered by our BC promise, but the file being present in `vendor/contao/core-bundle/src/Resources/contao/config` is not. In fact, it will no longer be there as of Contao 4.7.

**Comment by aschempp** [comment]
Well this way supports all Contao versions, including the ones with the BC break 😉

**Comment by leofeyer** [comment]
True 😊
