### ISSUE TITLE
Attribute not translated in Notification e-mails

### ISSUE THREAD

**Issue by xApep** [isotope/core#2368]
I have two attributes which are used as variants of a product.
- Size
- Color

Using translation to translate from English to Slovenian which works as it should in front-end
![image](https://user-images.githubusercontent.com/1315340/188822317-afeda5fd-e588-479e-ac6d-e18b93dbc468.png)

Setting up order confirmation e-mail in Notification Center, with Slovenian language fallback the attributes when receiving e-mail are not translated. 

![image](https://user-images.githubusercontent.com/1315340/188822962-e60447a5-e144-4da0-b4c8-facbb9a77647.png)

Using Isotope 2.8.7 and Contao 4.12.2

**Comment by aschempp** [comment]
This is inside the collection template, right?

I don't think this will be possible to fix unfortunately. Attribute labels are loaded when the attributes are loaded based on the current page language, and there is no way to re-translate them for a notification language. The only option I can think of is using an insert tag for the label instead of the actual name, but I assume you have the default code to generate the options in the template?

**Comment by xApep** [comment]
Indeed.

Do you have any suggestion how to achieve that with insert tags?

**Comment by aschempp** [comment]
Not out of my head, but somehow by adjusting the templates. Maybe use real translation files in Contao instead of the given attribute labels.
