### ISSUE TITLE
Error on attribute checkbox when using "single option"

### ISSUE THREAD

**Issue by xApep** [isotope/core#2373]
If you select options source "Attribute Name (Single Option)" then it throws an error:
`An exception occurred while executing a query: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'inquiry_only' at row 1`

![image](https://user-images.githubusercontent.com/1315340/191050578-c5f8c792-5f52-47e1-af5f-ecc6df5887e2.png)

Contao: 4.13.8
Isotope: 2.8.7

**Comment by aschempp** [comment]
did you previously use options on the same attribute?

**Comment by xApep** [comment]
Yes/No.
 I have tried both ways; 
changing existing one; 
creating new attribute and selecting Attribute name (single option) on the first "run"...but it always throw the same error.

**Comment by aschempp** [comment]
thanks, that should help me localise the issue. It most certainly should not happen for a new attribute.

**Comment by ameotoko** [comment]
I just encountered this problem when I created a new "Checkbox menu" attribute and then selected "Single option".

The problem seems to be, that a column for a new attribute (or maybe only checkbox, I didn't test much) is created with default value of `null`. When you then select "Single option", Isotope tries to modify column to `char(1) NOT NULL` and fails, since all the rows already have `null` as the value.

Running `UPDATE tl_iso_product SET your_attribute = ''` and then refreshing the backend page fixed the problem.

**Comment by aschempp** [comment]
But that would be a manual query, right? Any idea how we could do that "automatically"?

**Comment by ameotoko** [comment]
I think, the only case where it should be fixed automatically is when user creates a new attribute and then immediately changes the attribute type. Isotope could quickly check whether the column has any values other than `null`, and if not - perform the above fix automatically. If column has any data already, then error message could be shown in backend.

In fact, it might make sense to prohibit changing attribute type altogether in this case. For example, by making type selector `disabled` on load.

**Comment by aschempp** [comment]
fixed in 1bba29bbcd61e6e01de5450e3f74f2ed086492e2
