### ISSUE TITLE
Ireland Missing Munster Province and it's related Counties

### ISSUE THREAD

**Issue by spirescreative** [isotope/core#2529]
When setting up the Store Configuration for Ireland, the "State" listing is missing the entirety of Munster Province, which includes counties such as Cork, Kerry and Limerick.

Is it possible to modify the Isotope Store Configuration dropdowns manually to include the missing Province and Counties?

**Comment by aschempp** [comment]
Yes you can modify it manually. The data is located in [`system/modules/isotope/languages/en/subdivisions.php`](https://github.com/isotope/core/blob/2.8/system/modules/isotope/languages/en/subdivisions.php). You can create your own `/contao/languages/en/subdivisions.php` in your project and add the necessary options.

However, I would also be interested if these provinces have been added recently? Because the data is based on Wikipedia/ISO standards, so I wonder why these are missing there?

**Comment by fritzmg** [comment]
It's not missing:

https://github.com/isotope/core/blob/2c3756132cd6d9fc7a86a7d7a7ac1cfaa8879e58/system/modules/isotope/languages/en/subdivisions.php#L1899

**Comment by spirescreative** [comment]
None of the counties in Munster Province are listed which is likely why the the Province doesn't show in the store config. The counties would need to be added under Munster, is my thinking.

**Comment by spirescreative** [comment]
> Yes you can modify it manually. The data is located in [`system/modules/isotope/languages/en/subdivisions.php`](https://github.com/isotope/core/blob/2.8/system/modules/isotope/languages/en/subdivisions.php). You can create your own `/contao/languages/en/subdivisions.php` in your project and add the necessary options.

Thank you for locating the data! I wasn't looking under languages for post locations. This should help and I believe that if I manually add the counties for Munster Province the same as the other counties are listed, it should populate. 

Looks like the counties of Munster are missing, not the Province itself as @fritzmg pointed out.
https://en.wikipedia.org/wiki/Provinces_of_Ireland
https://en.wikipedia.org/wiki/Munster

**Comment by aschempp** [comment]
Thanks for the explanation! I have updated the data in 967a687acef57ef7dde0ef2adf3d850d240131dd from https://en.wikipedia.org/wiki/ISO_3166-2:IE
